name: Docker Image CI
env:
  APP_NAME: ubuntu-glinet-bulid-axt1800
  DOCKERHUB_REPO: loophank/ubuntu-glinet-bulid-axt1800
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
    -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
    -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: |
            linux/386
            linux/amd64
          push: true
          build-args: |
            APP_NAME=${{ env.APP_NAME }}
            APP_VERSION=${{ env.APP_VERSION }}
          tags: |
            ${{ env.DOCKERHUB_REPO }}:latest
            ${{ env.DOCKERHUB_REPO }}:${{ env.APP_VERSION }}
